name: virtual_exercise_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.2.0
  video_player: ^2.9.5
  path_provider: ^2.1.5
  camera: ^0.10.0+3
  firebase_core: ^3.14.0
  url_launcher: ^6.1.12
  firebase_auth: ^5.5.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  mediapipe_core: ^0.0.1
  web_socket_channel: ^3.0.3
  google_mlkit_pose_detection: ^0.10.0
  google_mlkit_commons: ^0.6.0
  animated_icon: ^0.0.5
  http: ^0.13.6
  collection: ^1.17.0
  time: ^2.1.5
  flutter_secure_storage: ^9.2.4
  flutter_tts: ^4.2.3
  uuid: ^4.5.1
  intl: ^0.20.2
  cloud_firestore: ^5.6.11
  ffmpeg_kit_flutter_new: ^2.0.0
  image_picker: ^1.0.7
  video_thumbnail: ^0.5.3
  image: ^4.1.7
  tflite_flutter: ^0.10.4

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/homepage-animation.json
    - assets/videos/
    - assets/models/exercise_classification_model.tflite

  fonts:
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
          weight: 700